Feat add Rax Styles
raxjs/rax-vscode-extensions pull request #14
Opened 2020-01-09 08:08 UTC by fyangstudio

### Features
1. Hover widget
2. Click to definition
3. Auto complete

![img01](https://img.alicdn.com/tfs/TB1WYmQtuH2gK0jSZFEXXcqMpXa-1488-836.gif)

2020-01-09 13:30 UTC, yuanyan approved these changes

2020-01-09 14:46 UTC, wssgcg1213 commented on extensions/vscode-rax-styles/src/findStyleSelectors.js
> +    })
少分号, 看一下lint规则是不是没配?

2020-01-09 14:48 UTC, wssgcg1213 requested changes

2020-01-09 14:48 UTC, wssgcg1213 commented on extensions/vscode-rax-styles/src/index.js
> +  // match styles.xxx
这里 `styles.` 是约定吗?  有没有可能做成确定 style Identifier 的名字

2020-01-10 02:12 UTC, fyangstudio commented on extensions/vscode-rax-styles/src/index.js
> +  // match styles.xxx
👍

2020-01-10 16:12 UTC, yuanyan commented on extensions/vscode-rax-styles/src/findStyleSelectors.js
> +const fs = require('fs-extra');
引入 fs-extra 的必要性？

2020-01-10 16:14 UTC, yuanyan commented on extensions/vscode-create-rax/client/src/pages/Create/isEnLang.js
> +  isEnLang = (window.__VSCODE__.env.language || '').indexOf('en') === 0;
在我的vscode上好像没有 env.language, 导致默认显示了中文，是电脑环境差异？

2020-01-10 16:16 UTC, yuanyan commented on extensions/vscode-create-rax/client/src/pages/Create/isEnLang.js
> +  isEnLang = (window.__VSCODE__.env.language || '').indexOf('en') === 0;
![image](https://user-images.githubusercontent.com/677114/72168168-96f0cb80-3407-11ea-8eff-8c7bfb609f6b.png)

2020-01-11 06:27 UTC, fyangstudio commented on extensions/vscode-create-rax/client/src/pages/Create/isEnLang.js
> +  isEnLang = (window.__VSCODE__.env.language || '').indexOf('en') === 0;
在 #11 中修复了这个问题。 webview 中的 vscode 没有 env 属性，改为上层获取 vscode.env.language 后传入页面

2020-01-14 05:40 UTC, yuanyan commented on README.md
> +## 3. Rax Styles
Rax className

2020-01-14 05:41 UTC, yuanyan commented on extensions/vscode-rax/package.json
> +    "Rax.vscode-rax-styles"
Rax.vscode-rax-classname

2020-01-14 05:42 UTC, yuanyan commented on extensions/vscode-rax-styles/src/index.js
> +    return new vscode.Hover(`**styles:**  \n ${styles.join('  \n ')} `);
直接展示原始代码会更直接：
```
.home {
  
}
```

2020-01-14 06:00 UTC, fyangstudio commented on README.md
> +## 3. Rax Styles
className 可能会和  https://www.npmjs.com/package/classnames 这个包的意义有些混淆。
改成： vscode-rax-css-class

2020-01-14 08:04 UTC, yuanyan approved these changes

2020-01-14 08:05 UTC, merged